
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 28;
  public static final int FIM_BLOCO = 21;
  public static final int ELSE = 8;
  public static final int PLUS = 3;
  public static final int OR = 29;
  public static final int RPAREN = 27;
  public static final int EQUAL = 14;
  public static final int SEMI = 2;
  public static final int WHILE = 10;
  public static final int SCANF = 12;
  public static final int GREATER = 16;
  public static final int INICIO_BLOCO = 20;
  public static final int IF = 7;
  public static final int LPAREN = 26;
  public static final int PRINTF = 11;
  public static final int INTEIRO = 22;
  public static final int CARACTER = 24;
  public static final int STRING = 13;
  public static final int LESSTHAN = 17;
  public static final int EOF = 0;
  public static final int LESSTHANEQ = 19;
  public static final int DIVIDE = 6;
  public static final int GREATEREQ = 18;
  public static final int MINUS = 4;
  public static final int NUMERO = 31;
  public static final int TYPESTRING = 25;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 30;
  public static final int DIFF = 15;
  public static final int FOR = 9;
  public static final int REAL = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "PRINTF",
  "SCANF",
  "STRING",
  "EQUAL",
  "DIFF",
  "GREATER",
  "LESSTHAN",
  "GREATEREQ",
  "LESSTHANEQ",
  "INICIO_BLOCO",
  "FIM_BLOCO",
  "INTEIRO",
  "REAL",
  "CARACTER",
  "TYPESTRING",
  "LPAREN",
  "RPAREN",
  "AND",
  "OR",
  "IDENTIFICADOR",
  "NUMERO"
  };
}

